name: TasikNewsAuto

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install node-fetch
      run: npm install node-fetch

    - name: Generate News
      run: node generator/generate-news.js

    - name: Commit Update
      run: |
        git config --global user.name "newsbot"
        git config --global user.email "bot@github.com"

        git add .

        git diff --quiet && git diff --staged --quiet || git commit -m "auto news update"

        git push
