name: TasikNewsAuto

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Run generator
      run: node generator/generate-news.js

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add .

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto news update"
          git push
        fi
