name: TasikNewsAuto

on:
 schedule:
  - cron: "0 */2 * * *"

jobs:

 build:

  runs-on: ubuntu-latest

  steps:

  - name: Checkout Repository
    uses: actions/checkout@v3

  - name: Setup NodeJS
    uses: actions/setup-node@v3

  - name: Install Dependencies
    run: npm install node-fetch

  - name: Generate News Articles
    run: node generator/generate-news.js

  - name: Commit Update
    run: |
      git config --global user.name "newsbot"
      git config --global user.email "bot@github.com"

      git add .
      git commit -m "auto news update"
      git push
